namespace: 'openshift-storage'
clusterMonitoring: 'true'

channel: 'stable-4.8'
installPlanApproval: 'Automatic'
name: 'ocs-operator'
source: 'redhat-operators'
sourceNamespace: 'openshift-marketplace'
startingCSV: