# Create Operator Group for OCS Operator.
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.namespace }}-operatorgroup
  namespace: {{ .Values.namespace }}
spec:
  targetNamespaces:
    - {{ .Values.namespace }}